### ISSUE TITLE
Provide reference to FooSoft/vim-argwrap ?

### ISSUE THREAD

**Issue by shea-parkes** [ColinKennedy/vim-python-style-swapper#1]
I find the functionality that this plugin supplies to be **really** helpful.  I've been using this plugin to provide it so far: https://github.com/FooSoft/vim-argwrap

You absolutely don't have to do this, but it might be useful to include a link and a compare/contrast in the Readme.

I like that `vim-argwrap` works on more than just Python, but I like the idea that this plugin is potentially smarter about Python (which I work in a lot).

Thanks again for putting this out here!

**Comment by ColinKennedy** [comment]
The reason that I wrote this repo was basically because I couldn't find an equivalent plugin when I searched for one. (i.e. searching "argument style changer vim" / "vim list multiline plugin" doesn't even show it).

Thank you for posting this. I'll try it out for a couple weeks. Depending on how it goes, I may just to change the readme to encourage people to use vim-argwrap, instead

**Comment by shea-parkes** [comment]
There are so many plugins out there I sympathize with how hard it can be to find what you're looking for.  It's also sometimes nice to know there are a couple viable alternatives for a certain piece of functionality.  Best of luck sir.

**Comment by ColinKennedy** [comment]
I've been using FooSoft/vim-argwrap for many months and have had no issues. Marking this repository as deprecated. Thank you for the link, shea!
